# Minimal travis config for running tox and uploading code coverage

dist: xenial
language: python
cache: pip
python: "3.7"

# Install system packages
before_install: sudo apt-get install ffmpeg librsvg2-bin

# Install deps
install: pip install -U tox-travis codecov

# Run tests
script: tox

