name: Test and Lint

on: pull_request

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Install package dependencies
      uses: mstksg/get-package@v1
      with:
        brew: ffmpeg librsvg
        apt-get: ffmpeg librsvg2-bin
    - name: Test with pytest
      run: |
        pytest tests/

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set up Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Lint with flake8
      run: |
        flake8 stress_fiber --count --verbose --max-line-length=88 --show-source --statistics
